# Generated by Django 4.1.4 on 2022-12-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mineral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atomicWeight', models.IntegerField()),
                ('pricePerKg', models.IntegerField()),
                ('crystalStructure', models.TextField()),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
