# Generated by Django 4.1.4 on 2022-12-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineral',
            name='mineralType',
            field=models.TextField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='crystalStructure',
            field=models.TextField(max_length=40),
        ),
    ]
